version: '3'
services:
  app:
    build: 
      context: .
    ports:
      - 6969:6969
    environment:
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_PORT: ${PG_PORT}
      API_KEY: ${API_KEY}
      PORT: ${PORT}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASS: ${USER_PASS}
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata:
networks:
  zeotapnetwork:
